# Generated by Django 3.1.2 on 2021-11-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloprincipal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadlotes', models.IntegerField()),
                ('horasalquiler', models.IntegerField()),
                ('fechareserva', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Andamio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadtotal', models.CharField(max_length=50)),
                ('nombrelote', models.CharField(max_length=50)),
                ('tipoandamio', models.IntegerField(choices=[[0, 'Andamio de fachada'], [1, 'Andamio multidireccional'], [2, 'Torres móviles'], [3, 'Andamios tubulares'], [4, 'Andamios colgantes'], [5, 'Andamio de boriquetas'], [6, 'Andamio de trabajo'], [7, 'Andamio de caballete']])),
                ('valorhora', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('tipos', models.IntegerField(choices=[[0, 'Empresa'], [1, 'Particular']])),
                ('clasificacion', models.IntegerField(choices=[[0, 'bronce'], [1, 'plata'], [2, 'oro'], [3, 'platino']])),
            ],
        ),
        migrations.RemoveField(
            model_name='pool',
            name='token',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='andamio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moduloprincipal.andamio'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moduloprincipal.cliente'),
        ),
    ]
